groups:
  Guest:
    fancyName: "§r§l§7Guest"
    permissions:
      - "core.groups"
join:
  message-server: "§r§a + {name}"
  message-player:
    - "§r§fWelcome, {name}"
    - "§r§fKitPvP!"
  title: "Welcome!"
  subtitle: "Hi!"
quit-message: "§r§c - {name}"
commands:
  setgroup:
    group-set: "Your group has been set to: {group}"
kits:
  drop-ground: "You did not have enough inventory space, so some items have dropped on the ground."
  still-on-cooldown: "You are still on cooldown for this kit!"
  types:
    Swordsman:
      items:
        0:
          id: 267
          meta: 0
          enchantments:
            0:
              id: 16
              level: 1
          custom-name: "Sword"
          custom-lore:
            - "lore1"
            - "lore2"
      description: "A kit for basic PvP"
      coolDown: 60
    name:
      description: "sand"
      items:
        0:
          id: 12
          meta: 0
      coolDown: 10
zones:
  cannot-hit: "You may not hit players in this area!"
death:
  unknown-reason: "{name} has died"
  killed: "{name} has been killed by {killer}"
warps:
  warp-success: "You have successfully warped"
  warp-fail: "You do not have permission to use this warp"
  types:
    name:
      position: "10:10:10"
      world: "world"
    name2:
      position: "10:10:10"
      world: "world"
      permission: "perm.perm"

